### ISSUE TITLE
multi monitor mess

### ISSUE THREAD

**Issue by rizajur** [material-shell/material-shell#945] opened 2023-01-31 10:41 UTC
**Describe the bug**
multi monitor usage results in very unpleasing bugs and basically breaks the whole workflow of this wm

**Expected behavior**
No glitches like in the screenshot below , flashes  ( spawn windows on wrong monitor than quickly move them to the right one which results in a flash animation every time you open a window) etc

**Screenshots**

![c](https://user-images.githubusercontent.com/123980461/215737362-edb7e1c5-ae7f-4c9a-88da-1d5d80533dfd.png)

**To Reproduce**
- Occurs on:
  - [ ] X.Org
  - [x] Wayland
- DE: GNOME 40.10
- Distro: AlmaLinux 9.1

The same / similar bugs exist on Gnome 43 Wayland ArchLinux 

- Steps to reproduce, if applicable:
1. Step 1 Use multi monitor
2. Step 2 Open windows
3. Bug

**Current commit** - Gnome Extension Store install

**This looks interesting:**

```
 meta_display_get_monitor_scale: assertion 'monitor >= 0 && monitor < n_logical_monitors' failed
 meta_display_get_monitor_scale: assertion 'monitor >= 0 && monitor < n_logical_monitors' failed
```

**Log data**
Output from `journalctl /usr/bin/gnome-shell`:
```
Jan 31 01:14:28 tower gnome-shell[11766]: JS ERROR: Error: Virtual function not implemented: Class ClutterClickAction doesn't implement long_press
                                          vfunc_long_press@/usr/share/gnome-shell/extensions/material-shell-fix@papyelgringo/extension.js:537:17
Jan 31 01:14:28 tower gnome-shell[11766]: JS ERROR: Error: Virtual function not implemented: Class ClutterClickAction doesn't implement clicked
                                          vfunc_clicked@/usr/share/gnome-shell/extensions/material-shell-fix@papyelgringo/extension.js:533:17
Jan 31 01:14:28 tower gnome-shell[11766]: Timelines with detached actors are not supported
Jan 31 01:14:28 tower gnome-shell[11766]: Timelines with detached actors are not supported
Jan 31 01:14:28 tower gnome-shell[11766]: Timelines with detached actors are not supported
Jan 31 01:14:29 tower gnome-shell[11766]: meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
Jan 31 01:14:29 tower gnome-shell[11766]: Meta window: vlc-63662-284 title='Something - VLC media player' dialog=false
Jan 31 01:14:29 tower gnome-shell[11766]: Meta window: librewolf-75848-359 title='Something — LibreWolf' dialog=false
Jan 31 01:14:29 tower gnome-shell[11766]: Meta window: gnome-tweaks-82640-386 title='GNOME Tweaks' dialog=false
Jan 31 01:14:29 tower gnome-shell[11766]: Meta window: freetube-31370-189 title='Something - FreeTube' dialog=false
Jan 31 01:14:29 tower gnome-shell[11766]: Meta window: freetube-31370-329 title='Something - FreeTube' dialog=false
Jan 31 01:14:29 tower gnome-shell[11766]: Meta window: freetube-31370-351 title='Something - FreeTube' dialog=fa>
Jan 31 01:14:29 tower gnome-shell[11766]: Meta window: gnome-control-center-82515-385 title='Settings' dialog=false
Jan 30 22:33:17 tower gnome-shell[11766]: Window manager warning: WM_TRANSIENT_FOR window 0x1600327 for override-redirect window 0x1600338 is an override-redirect w>
Jan 30 22:33:17 tower gnome-shell[11766]: Window manager warning: WM_TRANSIENT_FOR window 0x1600327 for override-redirect window 0x1600344 is an override-redirect w>
Jan 30 22:35:10 tower gnome-shell[11766]: Window manager warning: Invalid WM_TRANSIENT_FOR window 0x1600008 specified for 0x1600368.
Jan 30 22:35:11 tower gnome-shell[11766]: Window manager warning: Invalid WM_TRANSIENT_FOR window 0x1600008 specified for 0x1600368.
Jan 30 22:37:23 tower gnome-shell[11766]: Window manager warning: Invalid WM_TRANSIENT_FOR window 0x1600008 specified for 0x1600372.
Jan 30 22:37:23 tower gnome-shell[11766]: Window manager warning: WM_TRANSIENT_FOR window 0x1600372 for override-redirect window 0x1600378 is an override-redirect w>
Jan 30 22:37:26 tower gnome-shell[11766]: meta_display_get_monitor_scale: assertion 'monitor >= 0 && monitor < n_logical_monitors' failed
Jan 30 22:37:26 tower gnome-shell[11766]: meta_display_get_monitor_scale: assertion 'monitor >= 0 && monitor < n_logical_monitors' failed
Jan 30 22:37:26 tower gnome-shell[11766]: START DRAG, 2, false
Jan 30 22:37:26 tower gnome-shell[11766]: START DRAG, 2, false
Jan 30 22:53:48 tower gnome-shell[11766]: Window manager warning: Invalid WM_TRANSIENT_FOR window 0x1600008 specified for 0x1600368.
Jan 30 22:53:48 tower gnome-shell[11766]: Window manager warning: Invalid WM_TRANSIENT_FOR window 0x1600008 specified for 0x1600368.
Jan 30 22:53:49 tower gnome-shell[11766]: Window manager warning: Invalid WM_TRANSIENT_FOR window 0x1600008 specified for 0x1600368.
Jan 30 22:53:51 tower gnome-shell[11766]: Window manager warning: Invalid WM_TRANSIENT_FOR window 0x1600008 specified for 0x1600368.
Jan 30 22:53:52 tower gnome-shell[11766]: Window manager warning: Invalid WM_TRANSIENT_FOR window 0x1600008 specified for 0x1600368.
Jan 30 22:53:54 tower gnome-shell[11766]: Window manager warning: Invalid WM_TRANSIENT_FOR window 0x1600008 specified for 0x1600368.
Jan 30 22:58:49 tower gnome-shell[11766]: meta_display_get_monitor_scale: assertion 'monitor >= 0 && monitor < n_logical_monitors' failed
Jan 30 22:58:49 tower gnome-shell[11766]: meta_display_get_monitor_scale: assertion 'monitor >= 0 && monitor < n_logical_monitors' failed
Jan 30 22:58:52 tower gnome-shell[11766]: Window manager warning: Invalid WM_TRANSIENT_FOR window 0x1600008 specified for 0x1600412.
Jan 30 22:58:59 tower gnome-shell[11766]: Window manager warning: Invalid WM_TRANSIENT_FOR window 0x1600008 specified for 0x1600412.
Jan 30 22:58:59 tower gnome-shell[11766]: Window manager warning: Invalid WM_TRANSIENT_FOR window 0x1600008 specified for 0x1600412.
Jan 30 22:59:00 tower gnome-shell[11766]: Window manager warning: Invalid WM_TRANSIENT_FOR window 0x1600008 specified for 0x1600412.
Jan 30 22:59:07 tower gnome-shell[11766]: Window manager warning: Invalid WM_TRANSIENT_FOR window 0x1600008 specified for 0x16005c7.
Jan 30 22:59:08 tower gnome-shell[11766]: Window manager warning: WM_TRANSIENT_FOR window 0x16005c7 for override-redirect window 0x16005cd is an override-redirect w>
Jan 30 22:59:08 tower gnome-shell[11766]: Window manager warning: WM_TRANSIENT_FOR window 0x16005c7 for override-redirect window 0x16005d3 is an override-redirect w>
Jan 30 22:59:09 tower gnome-shell[11766]: Window manager warning: WM_TRANSIENT_FOR window 0x16005d3 for 0x16005d9 window override-redirect is an override-redirect w>
Jan 30 23:16:32 tower gnome-shell[11766]: Window manager warning: Invalid WM_TRANSIENT_FOR window 0x1600008 specified for 0x1600368.
Jan 30 23:16:33 tower gnome-shell[11766]: Window manager warning: Invalid WM_TRANSIENT_FOR window 0x1600008 specified for 0x1600368.
Jan 30 23:16:33 tower gnome-shell[11766]: Window manager warning: Invalid WM_TRANSIENT_FOR window 0x1600008 specified for 0x1600368.
Jan 30 23:16:34 tower gnome-shell[11766]: Window manager warning: Invalid WM_TRANSIENT_FOR window 0x1600008 specified for 0x1600368.
```

hope this helps to finally resolve this issue.

**Comment by ValouBambou** [comment] 2023-02-06 10:57
I also got an issue on Gnome 43 on Wayland using Archlinux with a setup using 2 externals displays (also I use 2 extensions caffeine and clipboard indicator, I hope there are no conflicts with these). One is a Dell with resolution 1920x1080 and work as expected. The other one is an HP with a resolution of 1920x1200 and doesn't work as expected. The mouse is displayed at a position but there is an offset from its real position. This is especially inconvenient for firefox and other gui apps.

Here is also logs from `journalctl /usr/bin/gnome-shell`

```
Feb 06 11:34:58 valowo gnome-shell[1162]: Window manager warning: Overwriting existing binding of keysym ff54 with keysym ff54 (keycode 74).
Feb 06 11:35:30 valowo gnome-shell[1162]: Window manager warning: Ping serial 1968105 was reused for window W7, previous use was for window W8.
Feb 06 11:37:39 valowo gnome-shell[1162]: Trying to activate unmanaged window 'W8'
Feb 06 11:40:12 valowo gnome-shell[1162]: Trying to activate unmanaged window '0xa019a5'
Feb 06 11:41:34 valowo gnome-shell[1162]: Meta window: org.gnome.Software-1485-16 title='Software' dialog=false
Feb 06 11:41:34 valowo gnome-shell[1162]: Meta window: org.gnome.Extensions-3026-8 title='Extensions' dialog=false
Feb 06 11:41:34 valowo gnome-shell[1162]: Meta window: Navigator-1870-4 title='multi monitor mess · Issue #945 · material-shell/material-shell — Mozilla Firefox' dialog=false
Feb 06 11:41:34 valowo gnome-shell[1162]: Meta window: org.gnome.Settings-1803-1 title='Settings' dialog=false
Feb 06 11:41:34 valowo gnome-shell[1162]: Creating a new MsWindow for org.gnome.Software-1485-16
Feb 06 11:41:34 valowo gnome-shell[1162]: meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
Feb 06 11:41:43 valowo gnome-shell[1162]: Invalid window geometry for xdg_surface@40. Ignoring for now, but this will result in client termination in the future.
Feb 06 11:41:43 valowo gnome-shell[1162]: Meta window: Alacritty-11165-17 title='Alacritty' dialog=false
Feb 06 11:41:43 valowo gnome-shell[1162]: Meta window: Navigator-1870-4 title='multi monitor mess · Issue #945 · material-shell/material-shell — Mozilla Firefox' dialog=false
Feb 06 11:41:43 valowo gnome-shell[1162]: Meta window: org.gnome.Settings-1803-1 title='Settings' dialog=false
Feb 06 11:41:43 valowo gnome-shell[1162]: Meta window: org.gnome.Extensions-3026-8 title='Extensions' dialog=false
Feb 06 11:41:43 valowo gnome-shell[1162]: Creating a new MsWindow for Alacritty-11165-17
Feb 06 11:41:43 valowo gnome-shell[1162]: meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
Feb 06 11:41:55 valowo gnome-shell[1162]: Invalid window geometry for xdg_surface@40. Ignoring for now, but this will result in client termination in the future.
Feb 06 11:41:55 valowo gnome-shell[1162]: Meta window: Alacritty-11245-18 title='Alacritty' dialog=false
Feb 06 11:41:55 valowo gnome-shell[1162]: Meta window: Navigator-1870-4 title='multi monitor mess · Issue #945 · material-shell/material-shell — Mozilla Firefox' dialog=false
Feb 06 11:41:55 valowo gnome-shell[1162]: Meta window: org.gnome.Settings-1803-1 title='Settings' dialog=false
Feb 06 11:41:55 valowo gnome-shell[1162]: Meta window: org.gnome.Extensions-3026-8 title='Extensions' dialog=false
Feb 06 11:41:55 valowo gnome-shell[1162]: Creating a new MsWindow for Alacritty-11245-18
Feb 06 11:41:55 valowo gnome-shell[1162]: meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
Feb 06 11:45:06 valowo gnome-shell[1162]: Trying to activate unmanaged window '0xa02863'
Feb 06 11:46:15 valowo gnome-shell[1162]: Invalid window geometry for xdg_surface@40. Ignoring for now, but this will result in client termination in the future.
Feb 06 11:46:15 valowo gnome-shell[1162]: Meta window: Alacritty-11369-22 title='Alacritty' dialog=false
Feb 06 11:46:15 valowo gnome-shell[1162]: Meta window: org.gnome.Settings-1803-1 title='Settings' dialog=false
Feb 06 11:46:15 valowo gnome-shell[1162]: Meta window: org.gnome.Extensions-3026-8 title='Extensions' dialog=false
Feb 06 11:46:15 valowo gnome-shell[1162]: Meta window: Alacritty-11245-18 title='val@valowo:~' dialog=false
Feb 06 11:46:15 valowo gnome-shell[1162]: Meta window: Navigator-1870-4 title='multi monitor mess · Issue #945 · material-shell/material-shell — Mozilla Firefox' dialog=false
Feb 06 11:46:15 valowo gnome-shell[1162]: Creating a new MsWindow for Alacritty-11369-22
Feb 06 11:46:15 valowo gnome-shell[1162]: meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
Feb 06 11:51:24 valowo gnome-shell[1162]: Trying to activate unmanaged window '0xa03b9f'
Feb 06 11:51:27 valowo gnome-shell[1162]: Trying to activate unmanaged window '0xa04672'
Feb 06 11:51:45 valowo gnome-shell[1162]: Trying to activate unmanaged window '0xa05048'
```

**Comment by rizajur** [comment] 2023-02-07 17:49
this extensions should not be conflicts.
I will soon retry this on Gnome 3.38.5 (Debian 11)

@PapyElGringo everyone with a multi monitor setup has to decide either ditch others displays or get rid of material shell which is really sad since its so well working with one monitor. (as long as you use a stable gnome version)

**Comment by rizajur** [comment] 2023-02-07 18:01
https://github.com/material-shell/material-shell/issues/917 like there?

**Comment by ValouBambou** [comment] 2023-02-07 18:04
I cant see the mouse icon on the screenshots but the issue describded sounds really similar yes.

**Comment by rizajur** [comment] 2023-02-07 18:05
> this have been fixed by https://github.com/material-shell/material-shell/pull/936

https://github.com/material-shell/material-shell/issues/938 @PapyElGringo 

hmm this also sound similar like my issue but you see on my screenshot the screen is split and both windows are at the same time on the right side and left side is just empty

**Comment by PapyElGringo** [comment] 2023-02-07 18:39
The cursor issue is probably a side effect of the tiling failure.

I don't have two external monitors to try to reproduce the issue but maybe @HalfVoxel can?

**Comment by rizajur** [comment] 2023-02-12 19:33
@PapyElGringo  how much money more do you need to get a second monitor?  or is it a reason of philosophy? 

@HalfVoxel we would really appreciate it since this bugs render material-shell useless with multiple monitors.

**Comment by PapyElGringo** [comment] 2023-02-12 22:36
@rizajur I would like get an ultra wide monitor as I have a plan for them but I don't want to get a cheap garbage that I couldn't use for my daily need so it's a bit complicated since I currently have no revenues 😁
But crowdfunding it's probably coming soon stay tuned or if you want to help me fund it reach me in private 👍

**Comment by rizajur** [comment] 2023-02-13 15:09
@PapyElGringo  `BenQ EW3270U` is a good monitor for the price. 

>reach me in private

i already send you the amount the monitor is worth. but i will one more, my budget is bleed out since i donated around 1.5k last year. thinking about codeberg membership :D

**Comment by PapyElGringo** [comment] 2023-02-13 16:29
@rizajur I currently use Fedora Silverblue but any distro using recent gnome version is fine like Ubuntu or Arch / Manjaro

Multi-monitor support is mandatory but since you don't have last version of Material Shell it may not be broken :)

Ultra wide monitor support is another project and doesn't depend on multi-monitor work

> i already send you the amount the monitor is worth. but i will one more, my budget is bleed out since i donated around 1.5k last year to foss projects. thinking about codeberg membership :D
Wow thanks !! What donation canal do you plan to use?

**Comment by rizajur** [comment] 2023-02-13 17:16
tried its broken on every gnome version i tried (many).
I will go for bookworm debian.

>What donation canal do you plan to use?
Main i use crypto but codeberg membership need swift... weak

**Comment by rizajur** [comment] 2023-02-13 18:36
@PapyElGringo wow the next Debian Stable Release Codename: Bookworm will run on Gnome Version 43.2 please consider making it the main focus of support since Ubuntu LTS, PopOS, NixOS etc will adapt from Debian (running 6.1 kernel)

**Comment by PapyElGringo** [comment] 2023-02-16 14:32
@rizajur Because we are a Gnome Shell extension we have to follow the Gnome Shell released and since our code base cannot be keep compatibility with many gnome shell version we have no choice to ditch compatibility code after several releases otherwise we would have spaghetti code

We need to make independence moves and start our own independent project to be able to follow our own release schedule

**Comment by rizajur** [comment] 2023-02-17 03:38
>We need to make independence moves and start our own independent project to be able to follow our own release schedule

That part i sadly disagree. I mean if you are giga chad coder + 1 more chad (not me) i would agree try a own wm and ditch mutter (gnome) but currently i would say use Gnome Version 43.2 as next stable main focus of support in order to extend and close all the issues that filled up before we should migrate the project in my opinion.

Idk what the quickest way to stable is - maybe checkout https://github.com/herbstluftwm/herbstluftwm

**Comment by PapyElGringo** [comment] 2023-02-18 18:51
I'll use my tv to try reproduce the issue and no I don't know @jkitching what is he working on?

**Comment by rizajur** [comment] 2023-02-18 19:11
i just arrived on bookworm debian, i will hold onto my word.
after we have multi monitor support, we need more option.
i will try to connect next week / weekend on discord to make some noob stuff regarding minor design flaws etc. and could provide help for the structuring the next follow up points this project has to address in order to make progress that matters. 
jkitching is just a good coder around gnome.

**Comment by tiramiseb** [comment] 2023-02-19 09:14
I personally have very few problems regarding my multi-monitor setup with material shell.

I see only two issues that are bothering me:

- some apps don't open on the monitor I started them (they seem to be apps that somehow open "another window" than the one expected by the WM (I don't known how to express it in technical terms))
- sometimes I can't move windows from one monitor to another using the mouse (I haven't tried to understand precisely the problem, therefore I can't post an issue here)

BTW I use XOrg, not Wayland.

**Comment by rizajur** [comment] 2023-02-19 09:21
> sometimes I can't move windows from one monitor to another using the mouse (I haven't tried to understand precisely the problem, therefore I can't post an issue here)

hold the super key and then left click the title bar of the window if self and drag it to the other monitor

> some apps don't open on the monitor I started them (they seem to be apps that somehow open "another window" than the one expected by the WM (I don't known how to express it in technical terms))

@PapyElGringo this is a material shell issue i had multiple times and many others as well

**Comment by tiramiseb** [comment] 2023-02-19 09:38
> @tiramiseb hold the super key and then left click the title bar of the window if self and drag it to the other monitor

Nah, this is exactly what is not always working :-)
But as I said, it has not been annoying enough for me to take time to try to understand why...

**Comment by PapyElGringo** [comment] 2023-02-21 14:59
The work is happening here https://github.com/material-shell/material-shell/pull/949

**Comment by rizajur** [comment] 2023-02-21 16:20
I will start testing tomorrow, thanks.

**Comment by PapyElGringo** [comment] 2023-03-06 10:22
Most of the listed issues has been fixed on `Main`, please reopen individual issues for each of the remaining bugs if there is any.

**Closed by PapyElGringo** 2023-03-06 10:22 UTC
