### ISSUE TITLE
Window moves to other monitor when popup dialogs closing in IntelliJ Idea

### ISSUE THREAD

**Issue by chamika** [material-shell/material-shell#302] opened 2020-09-19 08:51 UTC
**Describe the bug**
I have set up the external monitor to be displayed on top and my laptop screen on the bottom and the primary display is my laptop screen.

When closing popup dialogs in IntelliJ Idea 2020.1, the window on the external monitor moves to the bottom screen. This is not happening to the all the popup dialogs but the behaviour is consistent for certain types of dialogs like update reminder.

**Expected behavior**
The window should stay in the same monitor and same workspace. 

**Screenshots**
[See this screencast](https://drive.google.com/file/d/1ziQZcgdSUCJaEuT10GkO6aFf64VCWWGX/view?usp=sharing)

**To Reproduce**
- Occurs on:
  - [x] X.Org
  - [ ] Wayland
- GNOME Shell version: 3.36.4
- Distro: Ubuntu 20.04
- Steps to reproduce, if applicable:
1. Set the external monitor on top and primary monitor on bottom from display settings
2. Open IntelliJ Idea (not the latest) and goto Help > Check for updates
3. Dialog will show to update the dialog
4. Click on "Remind Me later"
5. Check the IntelliJ Idea window place

**Current commit**
Installed from gnome-extensions page

**Comment by greek** [comment] 2020-09-21 17:00
can reproduce, this can happen with any application too apart from IntelliJ

**Comment by greek** [comment] 2020-09-21 17:04
whoops, this is a duplicate of #296, will close this one.

**Closed by greek** 2020-09-21 17:04 UTC
Labels: bug, reproductible
