### ISSUE TITLE
System Tray disappears on sleep

### ISSUE THREAD

**Issue by LiHRaM** [material-shell/material-shell#123] opened 2019-10-08 16:58 UTC
Hi. I'm running Pop!_OS 19.04, with Gnome 3.32.
## `git show`
```
commit 3130886e15a81f293b7f0947697f5869ee8d85df (HEAD -> master, origin/master, origin/HEAD)
Author: PapyElGringo <adrien.peslerbe@bemyeye.com>
Date:   Mon Sep 16 15:33:05 2019 +0200

    fix following current displayed window while reordering in maximize
```

## gnome-shell logs
 `journalctl /usr/bin/gnome-shell -xe | grep "Oct 09" >> logs.txt`
https://pastebin.com/KrzFRbgG
## Description
Whenever the computer wakes up from sleep, the widgets in the bottom left part of the screen are gone. Posted a screenshot demonstrating the problem.
This is a problem on both Wayland and Xorg.
Clicking the area has no effect.

![image](https://user-images.githubusercontent.com/25297553/66416028-3cf1fb80-e9fd-11e9-811e-b100959ec478.png)

## Steps to reproduce
1. Start computer
2. Verify that system tray is present
3. Sleep
4. Wake
5. System tray is gone

**Comment by LiHRaM** [comment] 2019-10-12 23:17
Note that this only happens when I trigger sleep by closing my laptop screen. Can't figure out how to reproduce it otherwise.

**Comment by codycraven** [comment] 2019-10-14 18:28
@LiHRaM, I encounter the same issue when I dock/undock from my external monitor. I believe it happens when the resolution changes. I also receive the inverse where the system tray will appear directly below the workspaces (instead of the bottom of the sidebar).

My guess is closing your laptop lid is triggering a resolution change before sleep and/or a resolution change upon opening the lid.

**Comment by LiHRaM** [comment] 2019-10-14 18:45
@codycraven Interesting! I tried reproducing by manually changing the resolution in my settings, but that didn't have the same effect. Are you able to reproduce the error that way?

**Comment by codycraven** [comment] 2019-10-14 19:11
No, I can't reproduce by changing resolution through normal display settings. In fact with further testing I can't reproduce from docking/undocking solely. 

First my setup:

- Laptop screen 1080p
- External display 4k

Doesn't reproduce:

1. Docked (external monitor on, laptop closed)
2. Open laptop lid (laptop display still off)
3. Undock external monitor (laptop display on, system tray in correct place)
4. Dock external monitor (laptop display off, external monitor on, system tray in correct place)

Reproduce missing system tray:

1. Docked (external monitor on, laptop closed)
2. Suspend
3. Undock external monitor (laptop closed)
4. Open laptop, resume (system tray missing, laptop display on)
6. Restart Xorg (system tray in correct place)

Reproduce system tray immediately below workspace icons:
TBD, I don't know reproduction steps yet

**Comment by LiHRaM** [comment] 2019-10-14 19:37
If you move all the code from the `init` function in `extension.js` down to `enable()`, does that fix the issue?

**Comment by codycraven** [comment] 2019-10-15 03:37
I've made the following change and will report back when I dock tomorrow morning.

```
diff --git a/extension.js b/extension.js
index d6e6bf0..8133d60 100644
--- a/extension.js
+++ b/extension.js
@@ -20,6 +20,13 @@ function init() {
     log('--------------');
     log('INIT EXTENSION');
     log('--------------');
+}
+
+// eslint-disable-next-line no-unused-vars
+function enable() {
+    log('----------------');
+    log('ENABLE EXTENSION');
+    log('----------------');
     Signals.addSignalMethods(Me);
     global.materialShell = Me;
     Me.stateManager = new StateManager();
@@ -32,13 +39,6 @@ function init() {
         new SuperWorkspaceModule(),
         new HotKeysModule()
     ];
-}
-
-// eslint-disable-next-line no-unused-vars
-function enable() {
-    log('----------------');
-    log('ENABLE EXTENSION');
-    log('----------------');
     Main.wm._blockAnimations = true;
     //Delay to wait for others extensions to load first;
     GLib.idle_add(GLib.PRIORITY_DEFAULT, () => {
```

**Comment by codycraven** [comment] 2019-10-16 03:15
@LiHRaM, confirmed above diff resolves both scenarios for me.

**Comment by PapyElGringo** [comment] 2020-06-10 09:12
With Material Shell v2 out this issue **SHOULD** be fixed.

**Closed by PapyElGringo** 2020-06-10 09:12 UTC
