### ISSUE TITLE
App launcher text

### ISSUE THREAD

**Issue by Wael2727** [material-shell/material-shell#442] opened 2020-10-28 16:13 UTC
I Don't take this as a bug, rather i take it as a displeasing experience added to the app launcher
I'm pretty sure this is either caused by failed anti-aliasing/compositor issues

![Screenshot from 2020-10-28 22-09-21](https://user-images.githubusercontent.com/47404953/97464180-a23ec480-1951-11eb-9875-56d2be140194.png)

```
Oct 28 22:11:26 bxrry gnome-shell[1134]: value "nan" of type 'gfloat' is invalid or out of range for property 'height' of type 'gfloat'
```

**Comment by lfom** [comment] 2020-10-28 17:28
This kinda of error can be caused by any extension, it might not be related to MS. Sometimes a screen element (actor) does not exist anymore, so its properties are unknown (nan value). If it does not crash the extension, it is harmless.

**Comment by Wael2727** [comment] 2020-10-28 18:24
i'm aware it doesn't crash Material Shell
i'm just saying that the text itself looks displeasing

**Comment by lfom** [comment] 2020-10-28 18:29
I was referring to the error log, what is probably not connected to how the text is rendered. If you are using fractional scaling, it may lead to reduced display sharpness.

**Comment by Wael2727** [comment] 2020-10-28 19:29
Well? any idea how to fix it? 
(i'm a noob)

**Comment by lfom** [comment] 2020-10-28 20:17
Disable fractional scaling? If other things look blurry, probably it's a system issue, not related to MS. Other extensions or Gnome Shell themes may interfere also.

**Comment by pedrorebelocosta** [comment] 2020-11-06 12:27
In my case the taskbar icon size was actually causing this to happen: I had it set to 49px but then I reset it back to 48px and all the text is crisp now... seems like this could be the root cause @PapyElGringo @Wael2727

**Comment by PapyElGringo** [comment] 2020-11-06 17:39
Thanks it's helped me to found the cause should be fixed

**Closed** 2020-11-06 17:38 UTC
