### ISSUE TITLE
Workspaces bar does not work with touch events

### ISSUE THREAD

**Issue by lfom** [material-shell/material-shell#382] opened 2020-10-07 21:15 UTC
**Describe the bug**
Workspaces bar does dot work with touch events: it is hard to select workspaces (most of the time it results in dragging an icon around), and it is not possible to activate Overview (search icon). Statusarea works fine, tho.

**Expected behavior**
It should be possible to use touch events normally, just as it works now with mouse clicks (at least).

**Screenshots**
N/A

**To Reproduce**
- Occurs on:
  - [x] X.Org
  - [x] Wayland
- GNOME Shell version: 3.36.3
- Distro: Pop!_OS 20.04
- Steps to reproduce, if applicable:
1. Start MS
2. Bug

**Current commit**
master: 6a9cd52c26b34116769a98922e8ab82ab793e8f0

**Log data**
No errors in log as far as I can tell...

**Comment by expeehaa** [comment] 2020-11-04 00:39
Using a Surface Go with openSUSE Tumbleweed, gnome 3.36 and material-shell version 9, I can't reproduce that bug.
The only thing that doesn't work for me is changing the order of workspace using the touch screen.

**Comment by PapyElGringo** [comment] 2020-11-09 11:32
Should be fixed

**Closed by PapyElGringo** 2020-11-09 11:32 UTC
Labels: bug, reproductible

**Comment by lfom** [comment] 2020-11-09 23:00
@PapyElGringo It seems to work now (at least on Wayland), but I also get this messages on log now (no crashes tho):

`
clutter_event_get_button: assertion 'event->type == CLUTTER_BUTTON_PRESS || event->type == CLUTTER_BUTTON_RELEASE || event->type == CLUTTER_PAD_BUTTON_PRESS || event->type == CLUTTER_PAD_BUTTON_RELEASE' failed
`

**Comment by PapyElGringo** [comment] 2020-11-09 23:20
Could you try to dig up a bit? It still crash for some users and I think it's related to this log... But since I don't have a touch screen it's hard for me to test... You could ask @jugenhacker on discord for more details check #452

**Comment by lfom** [comment] 2020-11-09 23:26
@PapyElGringo Maybe the bug is related to 3.38? It didn't crash here when I tested, I am still using 3.36.4.

**Comment by PapyElGringo** [comment] 2020-11-09 23:56
Could you try found the source of the log?

**Comment by PapyElGringo** [comment] 2020-11-10 12:38
I think I got it right now
