### ISSUE TITLE
`Click anywhere to launch` doesn't disapear from opened window

### ISSUE THREAD

**Issue by fahim44** [material-shell/material-shell#922] opened 2022-12-13 06:15 UTC
**Describe the bug**

Sometimes after successfully opening a new app (most of the time, if the app is running opening a new window of the same app) doesn't remove the `click anywhere to launch` dialog from the window & it floats over the active window. 

In X.Org, I can click into the window below, in Wayland, the click is directed toward the `click anywhere` dialog .

My layouts are `maximize window`

**Expected behavior**

The `click anywhere to launch` dialog removes after opening the window

**Screenshots**

![Screenshot from 2022-12-13 11-44-41](https://user-images.githubusercontent.com/18325625/207238231-e4f3778f-6385-4c9d-a0d3-64199571cca7.png)

**To Reproduce**
- Occurs on:
  - [X] X.Org
  - [X] Wayland
- GNOME Shell version: 43.2
- Material Shell version: 26
- Distro: Fedora Linux 37 (Workstation Edition)
- Steps to reproduce, if applicable:
1. Open an application to maximize the layout
2. Open another new window of the same application in the same workspace
3. See the logo of the app & the `click anywhere to launch` dialog persists on the newly opened window.

**Current commit**
Output from `git rev-parse --short HEAD`: `c7803af`

**Log data**
Output from `journalctl /usr/bin/gnome-shell`:
```
example log data
```

**Comment by stuartwdouglas** [comment] 2022-12-13 21:17
I saw this as well, also on Fedora. It has basically made it unusable for me.

**Comment by PapyElGringo** [comment] 2022-12-13 21:54
How do you open new window?

**Comment by stuartwdouglas** [comment] 2022-12-13 21:56
For me it was opening a new project in IntelliJ where this was most noticeable.

**Comment by fahim44** [comment] 2022-12-14 00:32
@PapyElGringo for example for IntelliJ IDEs: open any project, then go to file->open->select another project path->(a popup will appear)->select `open in new window` from the popup

**Comment by millaguie** [comment] 2022-12-14 08:20
same here, even some windows with running processes has this over and makes the whole thing unusable (I can hear a video in the browser covered with the layer). When I open a new application randomly it shows the layer over it or not. when disabled and re-enable the extension randomly hides some windows with the layer... 

I have tried the following:
* to clean up the installation and reinstall
* clean up all settings
* use git version (dbeb869)

**Comment by stuartwdouglas** [comment] 2022-12-14 08:23
I think this was caused by a Fedora update, rather than a change in Material shell, although TBH since updating to 37 I have had nothing but problems. Before this I was seeing wayland core dumps, ran `dnf update` in the hope it would improve stability, and then things got even worse.

**Comment by PapyElGringo** [comment] 2022-12-14 10:25
Can someone try `blind-fix-922` branch?

**Comment by stuartwdouglas** [comment] 2022-12-14 11:00
It's better, but still not correct. Now when I open a project I still get the 'click to launch' screen, where before it would just open, but at least now when you click it opens.

**Comment by stuartwdouglas** [comment] 2022-12-14 11:15
Spoke too soon, the first time I tried it it opened, the second project did not work.

**Comment by stuartwdouglas** [comment] 2022-12-14 12:06
Also when I re-opened Intellij to try again it just did not respond to the mouse at all. I am pretty sure this is related, I have had material shell disabled for the past few days and had this issue until I re-enabled it.

**Comment by millaguie** [comment] 2022-12-14 14:24
I'm having some positive results with:

```
gnome-extensions disable material-shell@papyelgringo && sleep 3 && gnome-extensions enable material-shell@papyelgringo
```

Sometimes it fails but after two or three times it use to work. Also, I have to do it almost every time I open new window

**Comment by PapyElGringo** [comment] 2022-12-14 15:33
Which is kind of annoying @millaguie xD
Can you all provide logs of the opening sequence?

**Comment by shiptelligence** [comment] 2022-12-14 18:23
Same problem here. Can't open chrome its completely usable. Where should I get the logs from for you?

Also material shell is crashing one out of three times when unlocking. I have disabled all other extensions and it still happens too often. Please let me know where to send you the logs for this too.

Thanks

**Comment by millaguie** [comment] 2022-12-15 12:38
> 



Not so helpful I think, here it is
[journal.log](https://github.com/material-shell/material-shell/files/10236980/journal.log)

**Comment by PapyElGringo** [comment] 2022-12-16 10:56
After updating my system I do reproduce your issue guys.
I'm currently investigating

**Comment by PapyElGringo** [comment] 2022-12-16 13:52
Can you guys try https://github.com/material-shell/material-shell/pull/923
It's should fix it

**Comment by PapyElGringo** [comment] 2022-12-16 22:08
Should be fixed in main branch ! Youhouu :partying_face:

**Closed by PapyElGringo** 2022-12-16 22:08 UTC

**Comment by millaguie** [comment] 2022-12-20 18:26
Seems to work here, thank you very much!
