### ISSUE TITLE
Clock numbers on left panel take primary UI color at startup

### ISSUE THREAD

**Issue by matguidi** [material-shell/material-shell#417] opened 2020-10-20 22:07 UTC
**Describe the bug**
When Material Shell is loaded, the numbers of the clock are not light gray like all other icons in the left panel, but they take the primary UI color (blue in my case). After a first click on the clock, the numbers' color is back to normal.

**Expected behavior**
The numbers of the clock should be light gray from the beginning.

**Screenshots**
Bottom of left panel at startup:
![Schermata del 2020-10-20 23-56-29](https://user-images.githubusercontent.com/59918868/96649204-f255cf80-1330-11eb-82bf-da0b98673b62.png)

Bottom of left panel after first click on the clock:
![Schermata del 2020-10-21 00-03-07](https://user-images.githubusercontent.com/59918868/96649224-fe419180-1330-11eb-9508-794aa6690eff.png)

**To Reproduce**
- Occurs on:
  - [ ] X.Org
- GNOME Shell version: 3.38
- Distro: Manjaro 20.1
- Steps to reproduce, if applicable:
1. Restart gnome-shell 
2. The clock numbers are blue
3. Click on the clock
4. The clock numbers are light gray

**Comment by lfom** [comment] 2020-10-21 06:20
Are you sure there is no pending notification when you click on the clock? It is the expected behavior in this case. You might need the latest version from master tho, with the latest commits, as I do not see it here...

**Comment by matguidi** [comment] 2020-10-21 08:54
Ok, I see. It might be because of notifications, although it's strange that at every startup there is an unread notification (but this is due to Gnome-shell, if anything, not Material Shell). I'll check this. If this is the expected behaviour, though, the primary UI color should be a rather light one by default.

**Comment by Luctins** [comment] 2020-10-22 13:41
I have the same issue. but this mostly happens when I restart the shell, not on boot.
![image](https://user-images.githubusercontent.com/4743486/96879788-d64a4f00-1452-11eb-9f5e-b3207339442a.png)

**Comment by greek** [comment] 2020-10-24 10:35
it seems that the color is applied when Do Not Disturb is turned on.

**Comment by lfom** [comment] 2020-10-24 18:18
This should have been fixed since https://github.com/material-shell/material-shell/commit/64773673f53b6abe369ccf92eeeb637d7ccc3466 (not on Gnome Shell Extensions site as of now), you can upgrade it manually or wait for a new release and close the issue if it works, please?

**Closed** 2020-11-02 22:46 UTC
Labels: bug
