### ISSUE TITLE
Allow hiding box in the middle of the screen

### ISSUE THREAD

**Issue by DrDoctor13** [material-shell/material-shell#56] opened 2019-07-11 01:37 UTC
The box in the middle of the screen is convenient for frequently used applications, but in dual-monitor setups, it is not always necessary. Can it possibly be hidden/invoked with a key shortcut?

**Comment by PapyElGringo** [comment] 2019-07-11 16:09
Well you are the second to ask that. I didn't planned to do that because it's against design but I'm very curious about the usecase???

**Comment by DrDoctor13** [comment] 2019-07-11 22:21
Perhaps it is a bit of a niche case, but when having two monitors, for example, I don't _need_ the box on both screens. And if I want a fully keyboard-centric workflow, a box in the middle of the screen that can only be interacted with via mouse is counterintuitive.

**Comment by cristhianbreunig** [comment] 2019-07-13 04:37
> Well you are the second to ask that. I didn't planned to do that because it's against design but I'm very curious about the usecase???

For me it would be good, because I would end up with situations like this:

![launcher](https://user-images.githubusercontent.com/38818343/61166987-0eec4080-a50e-11e9-9f87-a4c639a701bd.png)

And i think that the "launcher" should be exibited only when theres no aplication open or when the user click on the + button

**Comment by StanSvec** [comment] 2019-08-09 05:59
@paradoxxxzero  How is your fix supposed to work? Will it hide the box when an application is opened in the workspace?

**Comment by xsgb** [comment] 2020-01-08 15:03
I really love your work on this project, the whole concept is very smart and I find it has a real enhancement potential for graphical interfaces paradigms.

For my case too, I would like to have an option to disable or hiding the constantly open card application box in the background. Reasons are that I never use clickable launcher and use a transparent terminal. I kinda like to see always nothing but my wallpaper in the background. 

Cheers!

**Comment by pyro57** [comment] 2020-01-09 22:14
I opened the other issue that's linked here, but yeah having a dock like that in the middle for a keyboard centric workflow doesn't help much, and in the case of window gaps (for aesthetics) and transparent applications (like a lot of terminals) it can be unsightly and annoying.

**Comment by PapyElGringo** [comment] 2020-01-12 10:14
These gaps and transparency background issues will be fixed in the next release since the shortcut dialog will animate in/ou when needed.

**Comment by H0xL** [comment] 2020-03-27 01:58
Trying to permanently remove the code that displays the superworkspace categories. In WorkspaceCategories.js file, are there any manual ways to start removing or hiding the docks? I see the links to .svg files, and variables that populate it, my only leads. Sorry I'm a HUGE noob, but really enjoying implementing this in to Kali-Linux to get some WM action.

**Comment by raygervais** [comment] 2020-04-03 04:02
I look forward to being able to toggle the boxes as well!

**Comment by PapyElGringo** [comment] 2020-06-10 09:04
With Material Shell v2 out this issue **IS CONFIRMED** be fixed.

**Closed by PapyElGringo** 2020-06-10 09:04 UTC
