### ISSUE TITLE
Crashes sometimes when closing last window in the workspace.

### ISSUE THREAD

**Issue by marmotgary** [material-shell/material-shell#535] opened 2020-12-31 17:27 UTC
**Describe the bug**
This is relatively rare, but sometimes when I close the last window in the workspace, material shell crashes. Probably something to do with removing the workspace as it becomes empty?

**Expected behavior**
When closing last window in a workspace, it should open the app launcher? Sometimes a crash occurs, and material shell reboots.

**To Reproduce**
- Occurs on:
  - [x] X.Org
  - [ ] Wayland
- GNOME Shell version: 3.36
- Distro: Pop_Os! 20.10

**Current commit**
Im in commit 8e0180204f1f982d9f4181017f562afd8b2b7171

**Log data**
Output from `journalctl /usr/bin/gnome-shell`:
```
    joulu 31 17:39:23 pop-os gnome-shell[3270]: Can't update stage views actor MsMain is on because it needs an allocation.
    joulu 31 17:39:23 pop-os gnome-shell[3270]: Can't update stage views actor PrimaryMonitorContainer is on because it needs an allocation.
    joulu 31 17:39:23 pop-os gnome-shell[3270]: Can't update stage views actor MsWorkspaceActor is on because it needs an allocation.
    joulu 31 17:39:23 pop-os gnome-shell[3270]: Can't update stage views actor ClutterActor is on because it needs an allocation.
    joulu 31 17:39:23 pop-os gnome-shell[3270]: Can't update stage views actor MsApplicationLauncher is on because it needs an allocation.
    joulu 31 17:39:23 pop-os gnome-shell[3270]: Can't update stage views actor Gjs_widget_msApplicationLauncher_MsApplicationButtonContainer is on because it needs an allocation.
    joulu 31 17:39:23 pop-os gnome-shell[3270]: Timelines with detached actors are not supported
    joulu 31 17:39:23 pop-os gnome-shell[3270]: Timelines with detached actors are not supported
    joulu 31 17:39:23 pop-os gnome-shell[3270]: Timelines with detached actors are not supported
    joulu 31 17:39:23 pop-os gnome-shell[3270]: Timelines with detached actors are not supported
    joulu 31 17:39:23 pop-os gnome-shell[3270]: Timelines with detached actors are not supported
    joulu 31 17:39:23 pop-os gnome-shell[3270]: Timelines with detached actors are not supported
    joulu 31 17:39:23 pop-os gnome-shell[3270]: Timelines with detached actors are not supported
    joulu 31 17:39:23 pop-os gnome-shell[3270]: **
    joulu 31 17:39:23 pop-os gnome-shell[3270]: St:ERROR:../src/st/st-bin.c:206:st_bin_destroy: assertion failed: (priv->child == NULL)
    joulu 31 17:39:23 pop-os gnome-shell[3270]: Bail out! St:ERROR:../src/st/st-bin.c:206:st_bin_destroy: assertion failed: (priv->child == NULL)
    joulu 31 17:39:23 pop-os gnome-shell[3270]: == Stack trace for context 0x55fad6d82220 ==
    joulu 31 17:39:23 pop-os gnome-shell[3270]: #0   7ffffaba6210 b   /home/vile/.local/share/gnome-shell/extensions/material-shell@papyelgringo/src/layout/msWorkspace/msWorkspace.js:85 (2540f05b5330 @ 61)
    joulu 31 17:39:23 pop-os gnome-shell[3270]: #1   7ffffaba6950 b   /home/vile/.local/share/gnome-shell/extensions/material-shell@papyelgringo/src/manager/msWorkspaceManager.js:479 (2540f05b2560 @ 114)
    joulu 31 17:39:23 pop-os gnome-shell[3270]: #2   7ffffaba7090 b   /home/vile/.local/share/gnome-shell/extensions/material-shell@papyelgringo/src/manager/msWorkspaceManager.js:165 (2540f05b2fb0 @ 16)
    joulu 31 17:39:23 pop-os gnome-shell[3270]: #3   7ffffaba85e0 b   /home/vile/.local/share/gnome-shell/extensions/material-shell@papyelgringo/src/manager/msWorkspaceManager.js:114 (2540f05b31a0 @ 1258)
    joulu 31 17:39:23 pop-os gnome-shell[3270]: #4   7ffffaba86a0 b   self-hosted:850 (3051e7b076a0 @ 398)
    joulu 31 17:39:43 pop-os gnome-shell[161107]: Skipping parental controls support as it’s disabled
    joulu 31 17:39:44 pop-os gnome-shell[161107]: Unset XDG_SESSION_ID, getCurrentSessionProxy() called outside a user session. Asking logind directly.
    joulu 31 17:39:44 pop-os gnome-shell[161107]: Will monitor session 2
    joulu 31 17:39:44 pop-os gnome-shell[161107]: Telepathy is not available, chat integration will be disabled.
    joulu 31 17:39:44 pop-os gnome-shell[161107]: Some code accessed the property 'ENABLED_EXTENSIONS_KEY' on the module 'extensionSystem'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
    joulu 31 17:39:44 pop-os gnome-shell[161107]: Some code accessed the property 'Portion' on the module 'portion'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
```

**Comment by enigma0160** [comment] 2021-02-03 13:29
Affects me as well. Gnome shell freezes completely, doesnt restart. Mouse and keyboard unresponsive.
Only solution is to reboot the system.
Always happens when the window being closed is an application that runs in the terminal (vifm in my case)
 
Occurs on:
- [x] X.Org
- [x] Wayland

Extension release: 12
Gnome shell version: 3.38.3
OS: Fedora 33 Workstation

**Comment by PapyElGringo** [comment] 2021-02-03 16:15
@enigma0160 same log?
So you start vifm from a terminal you move it to another workspace you kill it and it's crash?

**Comment by smythed** [comment] 2021-02-03 20:08
I reproduced it easily. Once it blew up I was able to ctrl-c to and return to gnome login screen. Here's is a log file.
[mslog.log](https://github.com/material-shell/material-shell/files/5921182/mslog.log)

**Comment by enigma0160** [comment] 2021-02-04 03:26
> @enigma0160 same log?
> So you start vifm from a terminal you move it to another workspace you kill it and it's crash?

I didnt check my logs actually.
I am launching Vifm from directly from the launcher, here is the launcher entry:
```
[Desktop Entry]
Categories=System;FileTools;FileManager;Utility;ConsoleOnly;
Comment=Vifm Vi[m] like ncurses based file manager
Exec=vifm %F
GenericName=File Manager
Icon=vifm
Name=Vifm
Terminal=true
TryExec=vifm
Type=Application
Keywords=File;Directory;Browse;
MimeType=inode/directory;
```

**Comment by mickare** [comment] 2021-11-28 14:15
Hey, same bug for me as well...

**Describe the bug**
The gnome desktop crashes when all applications in the first workspace are closed and the second workspace (with active apps) is switched.

I have two monitors. The main monitor has two workspaces with applications running (firefox, vscode, etc). The second monitor has Spotify & Firefox.


**Expected behavior**
No crash.


**To Reproduce**
- Occurs on:
  - [ ] X.Org
  - [x] Wayland
- GNOME Shell version: 41.1
- Distro: 5.15.2-2-MANJARO
- Steps to reproduce, if applicable:
1. Two displays (primary & secondary)
2. Open apps in workspace 1 on primary
3. Open apps in workspace 2 on primary
4. Open apps on secondary
5. Close ALL apps in workspace 1 on primary
6. Switch to workspace 2
7. CRASH

**Current commit**
I have no exact commit id. 
The version is "17" in `metadata.json` from https://extensions.gnome.org/extension/3357/material-shell/ .

**Log data**

```
Nov 28 13:45:13 sol gnome-shell[2257]: Could not create transient scope for PID 4729: GDBus.Error:org.freedesktop.DBus.Error.UnixProcessIdUnknown: Process with ID 4729 does not exist.
Nov 28 13:45:13 sol gnome-shell[2257]: Timelines with detached actors are not supported
Nov 28 13:45:13 sol gnome-shell[2257]: Focus MsWindow, Get Started - Visual Studio Code
Nov 28 13:45:19 sol gnome-shell[2257]: Focus MsWindow, Mozilla Firefox
Nov 28 13:45:21 sol gnome-shell[2257]: Focus MsWindow, Terminal
Nov 28 13:46:42 sol gnome-shell[2257]: Focus MsWindow, Restore Session — Mozilla Firefox
Nov 28 13:46:44 sol gnome-shell[2257]: libinput error: event5  - HID 046a:0023: client bug: event processing lagging behind by 13ms, your system is too slow
Nov 28 13:46:44 sol gnome-shell[2257]: **
Nov 28 13:46:44 sol gnome-shell[2257]: St:ERROR:../gnome-shell/src/st/st-bin.c:206:st_bin_destroy: assertion failed: (priv->child == NULL)
Nov 28 13:46:44 sol gnome-shell[2257]: Bail out! St:ERROR:../gnome-shell/src/st/st-bin.c:206:st_bin_destroy: assertion failed: (priv->child == NULL)
Nov 28 13:46:44 sol gnome-shell[2257]: == Stack trace for context 0x559f0f638170 ==
Nov 28 13:46:44 sol gnome-shell[2257]: #0   559f1063d218 i   /home/mickare/.local/share/gnome-shell/extensions/material-shell@papyelgringo/extension.js:8308 (3da112fe6ec0 @ 110)
Nov 28 13:46:44 sol audit[2257]: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=4 subj==unconfined pid=2257 comm="gnome-shell" exe="/usr/bin/gnome-shell" sig=6 res=1
Nov 28 13:46:44 sol gnome-shell[2257]: #1   559f1063d168 i   /home/mickare/.local/share/gnome-shell/extensions/material-shell@papyelgringo/extension.js:9020 (3da112fe51f0 @ 114)
Nov 28 13:46:44 sol gnome-shell[2257]: #2   559f1063d0d8 i   /home/mickare/.local/share/gnome-shell/extensions/material-shell@papyelgringo/extension.js:8807 (3da112fe5bf0 @ 16)
Nov 28 13:46:44 sol gnome-shell[2257]: #3   7ffcc04d69e0 b   /home/mickare/.local/share/gnome-shell/extensions/material-shell@papyelgringo/extension.js:8778 (3da112fe5d80 @ 1312)
Nov 28 13:46:44 sol gnome-shell[2257]: #4   7ffcc04d7100 b   /home/mickare/.local/share/gnome-shell/extensions/material-shell@papyelgringo/extension.js:9032 (3da112fe5150 @ 17)
Nov 28 13:46:59 sol gnome-shell[5282]: Running GNOME Shell (using mutter 41.1) as a Wayland display server
```


**Stacktrace translated**

`St:ERROR:../gnome-shell/src/st/st-bin.c:206:st_bin_destroy: assertion failed: (priv->child == NULL)` --> [st-bin.c#L206](https://github.com/GNOME/gnome-shell/blob/main/src/st/st-bin.c#L206)

1. extension.js:8308 (3da112fe6ec0 @ 110) --> [msWorkspace.ts#L130](https://github.com/material-shell/material-shell/blob/79df9b6951eaa80a0447b6997c610f75f8a5befd/src/layout/msWorkspace/msWorkspace.ts#L130)
2. extension.js:9020 (3da112fe51f0 @ 114) --> [msWorkspaceManager.ts#L546](https://github.com/material-shell/material-shell/blob/79df9b6951eaa80a0447b6997c610f75f8a5befd/src/manager/msWorkspaceManager.ts#L546)
3. extension.js:8807 (3da112fe5bf0 @ 16) --> [msWorkspaceManager.ts#L211](https://github.com/material-shell/material-shell/blob/79df9b6951eaa80a0447b6997c610f75f8a5befd/src/manager/msWorkspaceManager.ts#L211)
4. extension.js:8778 (3da112fe5d80 @ 1312) --> [msWorkspaceManager.ts#L153](https://github.com/material-shell/material-shell/blob/79df9b6951eaa80a0447b6997c610f75f8a5befd/src/manager/msWorkspaceManager.ts#L153)
5. extension.js:9032 (3da112fe5150 @ 17) --> [msWorkspaceManager.ts#L561](https://github.com/material-shell/material-shell/blob/79df9b6951eaa80a0447b6997c610f75f8a5befd/src/manager/msWorkspaceManager.ts#L561)

**Related issues**
- https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/3245
- https://gitlab.gnome.org/World/ShellExtensions/desktop-icons/-/issues/220

**Comment by mickare** [comment] 2021-11-28 15:22
Let's see if what the guys at gnome-shell say... https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/2052

**Comment by mickare** [comment] 2021-11-28 23:00
It seems the root of the problem is that material-shell is not de-allocating/removing the children from objects of the type `Clutter.Actor`. This results in a crash when deleting the parent object.

I think the [proposed solution by carlosg](https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/2052#note_1322197) is that the `Clutter.Actor` classes implement the `vfunc_dispose()` method that call the `remove_child()` method.

For example:
- [msWorkspace.ts#L616](https://github.com/material-shell/material-shell/blob/79df9b6951eaa80a0447b6997c610f75f8a5befd/src/layout/msWorkspace/msWorkspace.ts#L616) `this.tileableContainer` and `this.panel` needs to be removed

**Comment by mickare** [comment] 2021-11-28 23:36
@smythed   @enigma0160  @marmotgary 
If you have the time, could you test my try-fix [branch fix/crash-missing-dealloc](https://github.com/mickare/material-shell/tree/fix/crash-missing-dealloc) ?

In a short test I could not reproduce the issue anymore.

**Comment by mickare** [comment] 2021-11-29 00:00
Please don't try my branch yet. It's broken. With it I can't open a new app on the second monitor.

**Comment by PapyElGringo** [comment] 2021-11-29 19:27
This should be fixed on main then?

**Comment by mickare** [comment] 2021-11-29 20:10
At least for me. I don't know about @smythed  @enigma0160  @marmotgary ?

**Closed** 2022-06-17 12:59 UTC
