### ISSUE TITLE
Opening Chromium from VS Code result in the launching application overlay to be stuck

### ISSUE THREAD

**Issue by thomasnappee** [material-shell/material-shell#930] opened 2022-12-21 15:45 UTC
**Describe the bug**

When I run my code in VS Code, it opens a Chromium window to exec my code. The launching application overlay (the one with the launching application logo and the "Click anywhere to launch" text) get stuck. My application is running behind the overlay, get the mouse focus (I can interact with). I just can't see my application because of the overlay. The problem not occur only with VS Code but seems to be more general when you particular applications from another app : launching Chromium or code from command line doesn't works as expected. But launching Firefox or Nautilus works

**Expected behavior**

I'm expecting the overlay to disappear when the application is launched

**Screenshots**

![Capture d’écran du 2022-12-21 16-28-42](https://user-images.githubusercontent.com/14976249/208942011-a69a8796-6bae-42cf-9a05-0bce90847b59.png)

**To Reproduce**
- Occurs on:
  - [X] X.Org
  - [ ] Wayland
- GNOME Shell version: 43.2
- Distro: Manjaro 22.0.0
- Steps to reproduce, if applicable:

You need to have particular source code that can be ran in an emulator or a browser from visual studio. But you maybe can try this since the problem do not occur only with VS Code
1. Open your terminal
2. Launch chromium or code from the command line
3. New window with launching application overlay opens
4. Even is the application is launched, the overlay doesn't disappear

**Current commit**

Not installed from git, but version seems to be 43-1

**Log data**
Output from `journalctl /usr/bin/gnome-shell`:
```
déc. 21 16:43:33 tamapc gnome-shell[1130]: Meta window: code-1672-2 title='box_decorations.dart - cv (Espace de travail) - Visual Studio Code' dialog=false
déc. 21 16:43:33 tamapc gnome-shell[1130]: Meta window: chromium (/tmp/flutter_tools.MODJGE/flutter_tools_chrome_device.KICKFF)-18345-30 title='Sans titre – Chromium' dialog=false
déc. 21 16:43:33 tamapc gnome-shell[1130]: Creating a new window for chromium (/tmp/flutter_tools.MODJGE/flutter_tools_chrome_device.KICKFF)-18345-30
déc. 21 16:43:33 tamapc gnome-shell[1130]: Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x564420929ad0] is on because it needs an allocation.
déc. 21 16:43:33 tamapc gnome-shell[1130]: Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x56441c1facc0] is on because it needs an allocation.
déc. 21 16:43:33 tamapc gnome-shell[1130]: Can't update stage views actor <unnamed>[<MsWindow>:0x56442052b160] is on because it needs an allocation.
déc. 21 16:43:33 tamapc gnome-shell[1130]: Can't update stage views actor <unnamed>[<MsWindowContent>:0x5644204acc30] is on because it needs an allocation.
déc. 21 16:43:33 tamapc gnome-shell[1130]: Can't update stage views actor <unnamed>[<ClutterClone>:0x56441fb91400] is on because it needs an allocation.
```

**Comment by PapyElGringo** [comment] 2022-12-21 15:49
Running the integrated Manjaro version? The bug is already fixed see #922

**Comment by thomasnappee** [comment] 2022-12-21 17:58
Yes I installed gnome-shell and the extension with pacman. I tried https://github.com/material-shell/material-shell/issues/922#issuecomment-1351494076 without success

**Comment by shiptelligence** [comment] 2022-12-27 16:55
I have another problem that is probably related. When splitting the screen with 3 windows and opening gnome settings. The mouse input is shifted to the window on the left. E.g. you click within gnome settings and the window on the left registers the input. Also gnome settings renders incorrectly until you leave split mode. I have also seen similar behavior in other apps such as files. Problem goes away in float mode.

One hint to the cause of the problem can be seen in the following two screenshots. First one was taken using selection mode. The second one is taken using window mode. It seems to suggest the app thinks it is full screen even when its not.
![Screenshot from 2022-12-27 11-53-01](https://user-images.githubusercontent.com/106002404/209697615-3ea7fa0d-8286-4a7a-8e77-acc2b2e52845.png)
![Screenshot from 2022-12-27 11-53-18](https://user-images.githubusercontent.com/106002404/209697634-84e7d9ae-688d-4c47-bdc0-e45e3d1e8c00.png)

**Comment by PapyElGringo** [comment] 2022-12-27 17:22
@shiptelligence I do reproduce I'll investigate

**Comment by PapyElGringo** [comment] 2023-01-06 18:22
This has been fixed by https://github.com/material-shell/material-shell/pull/936

**Closed by PapyElGringo** 2023-01-06 18:22 UTC
