### ISSUE TITLE
On suspension and then logging back in, all the windows are in one workspace

### ISSUE THREAD

**Issue by CactiChameleon9** [material-shell/material-shell#349] opened 2020-09-28 16:00 UTC
**Describe the bug**
When closing my laptop lid (I think suspends because fans and hdd stop), and opening it after a while and logging back in to gnome, I find all windows in the first workspace and the others deleted

**Expected behavior**
After signing back in they all windows should be in their own separate workspaces as I left them

**Screenshots**
Before:
[imagine a screenshot with organized workspaces with windows in them]
After:
[imagine a screenshot with a single workspace with all windows now in it]

**To Reproduce**
- Occurs on:
  - [?] X.Org
  - [X] Wayland
- GNOME Shell version: 3.38
- Distro: Alpine edge
- Steps to reproduce, if applicable:
1. Suspend
2. Log back in
3. Bug

**Current commit**
Output from `git rev-parse --short HEAD`: `c7803af`

**Log data**
Output from `journalctl /usr/bin/gnome-shell`:
```
openrc (not systemd) so N/A
```

**Comment by PapyElGringo** [comment] 2020-09-29 10:32
It is 100% productible?

**Comment by CactiChameleon9** [comment] 2020-09-29 15:02
I happens about half of the time, recently 3 mixed into 2, but 1 was left alone. It seems without pattern

**Comment by aaronjanse** [comment] 2020-09-30 06:38
It's 100% reproducible for me. I'm running x11 on Pop!_OS, running git commit 5f78f1efa209b29bfa7aba68380fc6ed6d6b86e0.

When I enter in my lockscreen password, my windows are normal momentarily, then almost all windows (across multiple workspaces) are all added as tabs in my 1st workspace.

P.S. Material Shell is super cool. I really like the simple mental model of windows while still having the non-simple, very useful features of GNOME such as a nice task bar with WiFi GUI etc. Material Shell got me to move to GNOME from i3 :-)

**Comment by aaronjanse** [comment] 2020-09-30 06:38
^GNOME shell version 3.36.3

**Comment by lfom** [comment] 2020-09-30 06:47
If you have other extensions enabled, did you try disabling all of them but Material Shell (restart the computer to make sure they aren't loaded)?

**Comment by thejaffinator** [comment] 2020-09-30 10:50
This is also happening for me, also on GNOME 3.36.3. The only exception that has stayed on its correct workspace so far is the GNOME file manager, otherwise all apps move to workspace 1.

**Comment by aaronjanse** [comment] 2020-09-30 12:49
I can reproduce this (every time) on NixOS with no extensions installed other than Material Shell. I also noticed that the GNOME Tweaks tool stayed in its place while everything else moved.

**Comment by lfom** [comment] 2020-09-30 13:38
If anyone cá get a log from gnome-shell, I think I have seen this once when the state could no be saved to ~/.cache.

**Comment by thejaffinator** [comment] 2020-09-30 14:18
From the point where the laptop was opened again:

> Sep 30 15:00:42 joe-work gnome-shell[22321]: END DISABLE EXTENSION
Sep 30 15:00:42 joe-work gnome-shell[22321]: Object St.Widget (0x559262f5aac0), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from C code>
Sep 30 15:00:42 joe-work gnome-shell[22321]: == Stack trace for context 0x559258e3e640 ==
Sep 30 15:00:42 joe-work gnome-shell[22321]: #0   559265190800 i   /usr/share/gnome-shell/extensions/desktop-icons@csoriano/desktopManager.js:755 (985f8b89088 @ 587)
Sep 30 15:00:42 joe-work gnome-shell[22321]: #1   559265190778 i   /usr/share/gnome-shell/extensions/desktop-icons@csoriano/extension.js:68 (985f8b79970 @ 12)
Sep 30 15:00:42 joe-work gnome-shell[22321]: #2   5592651906a0 i   resource:///org/gnome/shell/ui/extensionSystem.js:108 (98555264628 @ 394)
Sep 30 15:00:42 joe-work gnome-shell[22321]: #3   559265190610 i   resource:///org/gnome/shell/ui/extensionSystem.js:624 (9855526a8f8 @ 15)
Sep 30 15:00:42 joe-work gnome-shell[22321]: #4   7ffe28810e60 b   self-hosted:266 (2dacfc850538 @ 259)
Sep 30 15:00:42 joe-work gnome-shell[22321]: #5   559265190580 i   resource:///org/gnome/shell/ui/extensionSystem.js:623 (9855526a880 @ 98)
Sep 30 15:00:42 joe-work gnome-shell[22321]: #6   5592651904f0 i   resource:///org/gnome/shell/ui/extensionSystem.js:641 (9855526a970 @ 82)
Sep 30 15:00:42 joe-work gnome-shell[22321]: #7   7ffe28811d20 b   self-hosted:1009 (363764f84c40 @ 423)
Sep 30 15:00:42 joe-work gnome-shell[22321]: #8   7ffe28811e20 b   resource:///org/gnome/gjs/modules/core/_signals.js:133 (985552963d0 @ 427)
Sep 30 15:00:42 joe-work gnome-shell[22321]: #9   7ffe28812940 b   resource:///org/gnome/shell/ui/sessionMode.js:198 (7954cd26880 @ 286)
Sep 30 15:00:42 joe-work gnome-shell[22321]: #10   559265190390 i   resource:///org/gnome/shell/ui/sessionMode.js:159 (7954cd266a0 @ 40)
Sep 30 15:00:42 joe-work gnome-shell[22321]: #11   5592651902d8 i   resource:///org/gnome/shell/ui/screenShield.js:574 (7954cd13880 @ 191)
Sep 30 15:00:42 joe-work gnome-shell[22321]: #12   559265190218 i   resource:///org/gnome/shell/ui/screenShield.js:623 (7954cd138f8 @ 419)
Sep 30 15:00:42 joe-work gnome-shell[22321]: #13   559265190180 i   resource:///org/gnome/shell/ui/screenShield.js:222 (7954cd0ead8 @ 65)
Sep 30 15:00:42 joe-work gnome-shell[22321]: #14   7ffe28813620 b   self-hosted:1011 (363764f84c40 @ 454)
Sep 30 15:00:42 joe-work gnome-shell[22321]: #15   7ffe28813720 b   resource:///org/gnome/gjs/modules/core/_signals.js:133 (985552963d0 @ 427)
Sep 30 15:00:42 joe-work gnome-shell[22321]: #16   5592651900c8 i   resource:///org/gnome/shell/misc/loginManager.js:198 (985552065b0 @ 202)
Sep 30 15:00:42 joe-work gnome-shell[22321]: #17   7ffe288146f0 b   self-hosted:1013 (363764f84c40 @ 492)
Sep 30 15:00:42 joe-work gnome-shell[22321]: #18   7ffe28814800 b   resource:///org/gnome/gjs/modules/core/_signals.js:133 (985552963d0 @ 427)
Sep 30 15:00:42 joe-work gnome-shell[22321]: #19   559265190018 i   resource:///org/gnome/gjs/modules/core/overrides/Gio.js:169 (e08fc992880 @ 39)
Sep 30 15:00:42 joe-work gnome-shell[22321]: clutter_actor_destroy: assertion 'CLUTTER_IS_ACTOR (self)' failed
Sep 30 15:00:42 joe-work gnome-shell[22321]: Could not create transient scope for PID 59715: GDBus.Error:org.freedesktop.DBus.Error.UnixProcessIdUnknown: Process with ID 59715 does not exist.
Sep 30 15:00:42 joe-work gnome-shell[22321]: Could not create transient scope for PID 59717: GDBus.Error:org.freedesktop.DBus.Error.UnixProcessIdUnknown: Process with ID 59717 does not exist.
Sep 30 15:00:42 joe-work gnome-shell[22321]: Object .MatPanelButton (0x55925a502e40), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.

Beyond this, it's mostly a lot of the same - `Object .MatPanelButton (0x1234...) has already been deallocated`, followed by `_clutter_actor_fully_transform_vertices: assertion 'CLUTTER_IS_ACTOR (self)' failed`. This repeats a lot.

Following the MS extension being loaded, I get this: 

> Sep 30 15:02:00 joe-work gnome-shell[22321]: ----------------
Sep 30 15:02:00 joe-work gnome-shell[22321]: END EXTENSION LOADED
Sep 30 15:02:00 joe-work gnome-shell[22321]: ----------------
Sep 30 15:02:00 joe-work gnome-shell[22321]: value "-20.000000" of type 'gfloat' is invalid or out of range for property 'width' of type 'gfloat'
Sep 30 15:02:00 joe-work gnome-shell[22321]: value "-20.000000" of type 'gfloat' is invalid or out of range for property 'height' of type 'gfloat'
Sep 30 15:02:00 joe-work gnome-shell[22321]: value "-20.000000" of type 'gfloat' is invalid or out of range for property 'width' of type 'gfloat'
Sep 30 15:02:00 joe-work gnome-shell[22321]: value "-20.000000" of type 'gfloat' is invalid or out of range for property 'height' of type 'gfloat'
Sep 30 15:02:00 joe-work gnome-shell[22321]: value "-20.000000" of type 'gfloat' is invalid or out of range for property 'width' of type 'gfloat'
Sep 30 15:02:00 joe-work gnome-shell[22321]: value "-20.000000" of type 'gfloat' is invalid or out of range for property 'height' of type 'gfloat'
Sep 30 15:02:00 joe-work gnome-shell[22321]: value "-20.000000" of type 'gfloat' is invalid or out of range for property 'width' of type 'gfloat'
Sep 30 15:02:00 joe-work gnome-shell[22321]: value "-20.000000" of type 'gfloat' is invalid or out of range for property 'height' of type 'gfloat'
Sep 30 15:02:00 joe-work gnome-shell[22321]: value "-20.000000" of type 'gfloat' is invalid or out of range for property 'width' of type 'gfloat'
Sep 30 15:02:00 joe-work gnome-shell[22321]: value "-20.000000" of type 'gfloat' is invalid or out of range for property 'height' of type 'gfloat'
Sep 30 15:02:00 joe-work gnome-shell[22321]: Could not create transient scope for PID 59946: GDBus.Error:org.freedesktop.DBus.Error.UnixProcessIdUnknown: Process with ID 59946 does not exist.
Sep 30 15:02:00 joe-work gnome-shell[22321]: Could not create transient scope for PID 59947: GDBus.Error:org.freedesktop.DBus.Error.UnixProcessIdUnknown: Process with ID 59947 does not exist.
Sep 30 15:02:00 joe-work gnome-shell[22321]: Could not create transient scope for PID 59948: GDBus.Error:org.freedesktop.DBus.Error.UnixProcessIdUnknown: Process with ID 59948 does not exist.
Sep 30 15:02:00 joe-work gnome-shell[22321]: Could not create transient scope for PID 59949: GDBus.Error:org.freedesktop.DBus.Error.UnixProcessIdUnknown: Process with ID 59949 does not exist.
Sep 30 15:02:01 joe-work gnome-shell[22321]: Window manager warning: Overwriting existing binding of keysym 20 with keysym 20 (keycode 41).
Sep 30 15:02:01 joe-work gnome-shell[22321]: Window manager warning: Overwriting existing binding of keysym 64 with keysym 64 (keycode 28).
Sep 30 15:02:01 joe-work gnome-shell[22321]: Window manager warning: Overwriting existing binding of keysym 20 with keysym 20 (keycode 41).
Sep 30 15:02:04 joe-work gnome-shell[22321]: hideAppLauncher
Sep 30 15:02:04 joe-work gnome-shell[22321]: st_widget_get_theme_node called on the widget [0x559267aac950 Gjs_widget_msApplicationLauncher_MsApplicationLauncher.surface-darker] which is not in the stage.
Sep 30 15:02:04 joe-work gnome-shell[22321]: st_widget_get_theme_node called on the widget [0x559267aac950 Gjs_widget_msApplicationLauncher_MsApplicationLauncher.surface-darker] which is not in the stage.
Sep 30 15:02:04 joe-work gnome-shell[22321]: st_widget_get_theme_node called on the widget [0x5592661a5460 Gjs_widget_msApplicationLauncher_MsApplicationButtonContainer:first-child last-child] which is n>
Sep 30 15:02:04 joe-work gnome-shell[22321]: st_widget_get_theme_node called on the widget [0x559267aac950 Gjs_widget_msApplicationLauncher_MsApplicationLauncher.surface-darker] which is not in the stage.
Sep 30 15:02:04 joe-work gnome-shell[22321]: st_widget_get_theme_node called on the widget [0x5592661a5460 Gjs_widget_msApplicationLauncher_MsApplicationButtonContainer:first-child last-child] which is n>
Sep 30 15:02:04 joe-work gnome-shell[22321]: st_widget_get_theme_node called on the widget [0x5592661a74f0 StEntry.search-entry:indeterminate first-child ("")] which is not in the stage.
Sep 30 15:02:04 joe-work gnome-shell[22321]: st_widget_get_theme_node called on the widget [0x559267aac950 Gjs_widget_msApplicationLauncher_MsApplicationLauncher.surface-darker] which is not in the stage.
Sep 30 15:02:04 joe-work gnome-shell[22321]: st_widget_get_theme_node called on the widget [0x5592661a5460 Gjs_widget_msApplicationLauncher_MsApplicationButtonContainer:first-child last-child] which is n>
Sep 30 15:02:04 joe-work gnome-shell[22321]: st_widget_get_theme_node called on the widget [0x5592661a74f0 StEntry.search-entry:indeterminate first-child ("")] which is not in the stage.
Sep 30 15:02:04 joe-work gnome-shell[22321]: st_widget_get_theme_node called on the widget [0x5592661a8be0 StLabel.hint-text ("Type to search…")] which is not in the stage.
Sep 30 15:02:04 joe-work gnome-shell[22321]: st_widget_get_theme_node called on the widget [0x559267aac950 Gjs_widget_msApplicationLauncher_MsApplicationLauncher.surface-darker] which is not in the stage.
Sep 30 15:02:04 joe-work gnome-shell[22321]: st_widget_get_theme_node called on the widget [0x5592661a5460 Gjs_widget_msApplicationLauncher_MsApplicationButtonContainer:first-child last-child] which is n>
Sep 30 15:02:04 joe-work gnome-shell[22321]: st_widget_get_theme_node called on the widget [0x5592661a74f0 StEntry.search-entry:indeterminate first-child ("")] which is not in the stage.
Sep 30 15:02:04 joe-work gnome-shell[22321]: st_widget_get_theme_node called on the widget [0x5592661a6a70 StIcon.search-entry-icon:last-child] which is not in the stage.

It then proceeds to go through every app on the system, seemingly in order of most used to least used, with exactly the same messages. The log ends after that.

**Comment by lfom** [comment] 2020-09-30 17:16
> Sep 30 15:02:00 joe-work gnome-shell[22321]: value "-20.000000" of type 'gfloat' is invalid or out of range for property 'width' of type 'gfloat'

Thank you for the log. I don't see the error for the persistence file, only the line above may be pertinent. I am using MS with Pop!_OS 20.04 and I could not reproduce it either under XOrg or Wayland (my daily driver).

If anyone that has this issue is willing to do some debug, please try:

1. Disable MS in Extensions app (do not use Tweaks), move the file **~/.cache/material-shell@papyelgringo-state.json** somewhere else (or rename, or delete it), enable the MS again in Extensions and see if it works (if you cannot save the state anymore for any reason, disable MS again copy or rename back the original file, then start MS)
2. Please share the above file here (or anywhere you can link to) just before you lock/suspend, and then a full gnome-shell log and the result of `lsb_release -a`
3. Disable MS in Extensions app, backup your current version and then try my version from (you can check my commits in the tree, but this is the version I use myself):
https://github.com/lfom/material-shell/tree/master-fixes

**Comment by aaronjanse** [comment] 2020-09-30 20:14
Heads up, this does not happen for me when simply logging out. The problem is suspending then logging back in

**Comment by thejaffinator** [comment] 2020-10-01 08:26
Debug results:

1. Removing the cache json and re-enabling just generated a new cache file, so I assume there are no problems writing it.

2. The cached json: https://pastebin.com/V1kughJQ
The entire gnome-shell log, from the point of suspension to after resuming: https://pastebin.com/Rmx6p7MD
The output of lsb_release -a: `No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal`

3. I haven't got round to this yet, will update when I have time.

**Comment by lfom** [comment] 2020-10-01 17:06
@thejaffinator Thank you for the provided info. But it didn't add much information, please observe the info below:
- the cached json only shows two windows in just one workspace: to help figuring out this problem, we need the json before the system was locked/suspended and with windows in more than one workspace
- the log should include everything since the screen is locked/suspended until the windows are restores and the problem is observed.

**Comment by thejaffinator** [comment] 2020-10-01 17:28
Here is a cached json with apps across 5 workspaces: https://pastebin.com/hhgr3x1X

Re the log, that is everything from suspension to accessing the log after the system comes back up, the timestamp jumps before that point so the log I provided starts at the point of closing the lid.

**Comment by thejaffinator** [comment] 2020-10-01 17:33
Also in case it was unclear the first time due to not enough programs being open, here is the log with the same 5 workspaces as above active over suspension, all of which were compiled into workspace 1 upon reopening.

https://pastebin.com/aeWjXv9V

**Comment by lfom** [comment] 2020-10-01 17:54
@thejaffinator I see, thank you for the clarification. Do you have multiple displays? Are you running Gnome over XOrg or Wayland?

**Comment by thejaffinator** [comment] 2020-10-02 08:11
Just the single laptop display, and I'm running over XOrg.

**Comment by thejaffinator** [comment] 2020-10-02 08:23
Also, I just tried your version of MS, unfortunately it still behaves the same.

**Comment by PapyElGringo** [comment] 2020-10-02 08:57
I just pushed a new commit with debug logs, could you all pull and reproduce the issue and post the logs?

**Comment by thejaffinator** [comment] 2020-10-02 11:03
https://pastebin.com/h2LEsi49

I left in a few lines before the suspension process starts since I noticed the debug logs show workspace creation now. I had 5 workspaces open before closing the lid, and I was left with all windows on workspace 1 after resuming.

**Comment by PapyElGringo** [comment] 2020-10-02 12:11
Ok in your case it's seem that the issue is not restoring state but indeed to properly save the state. I added more logs in the last commits can you do the same step ?

**Comment by thejaffinator** [comment] 2020-10-02 15:13
https://pastebin.com/eXRUxiBZ

Same as before, the log starts with the creation of 5 workspaces before suspension. Interestingly, this time everything from workspaces 2-5 collapsed onto workspace 2 while workspace 1 was left intact.

**Comment by PapyElGringo** [comment] 2020-10-02 15:54
Ok thanks @thejaffinator the issue is clear now. We save the state after we have disabled the extension with a wrong value. I added some more logs to find the source. Could you do the same one more time?
Thanks !

**Comment by thejaffinator** [comment] 2020-10-02 16:24
Sure: https://pastebin.com/NSRbdhzF

As before, 5 workspaces go to 2.

**Comment by PapyElGringo** [comment] 2020-10-02 16:35
Ok the last commit should fixe the issue. Could you try again and post logs if still happening?

**Closed** 2020-10-02 16:34 UTC
