### ISSUE TITLE
Super+Space is common keyboard layout switch combination

### ISSUE THREAD

**Issue by r7sa** [material-shell/material-shell#309] opened 2020-09-21 14:55 UTC
**Describe the bug**
The Super+Space combination is interfered with keyboard switch layout.

**Expected behaviour**
The combination need to be changed for comfortable use this extension in case of multiple keyboard layouts.

**Comment by dwrolvink** [comment] 2020-09-21 17:56
Duplicate of https://github.com/material-shell/material-shell/issues/274

**Closed by dwrolvink** 2020-09-21 17:56 UTC
Labels: bug, reproductible

**Comment by dwrolvink** [comment] 2020-09-21 17:59
I've added your suggestion there as an action point. You can continue the discussion over there. @r7sa
