### ISSUE TITLE
App launcher does not show new applications.

### ISSUE THREAD

**Issue by expeehaa** [material-shell/material-shell#419] opened 2020-10-21 09:02 UTC
**Describe the bug**
When I installed epiphany, the stock gnome app launcher did show the app (after it updated the desktop database), but the material shell app launcher did not.

**Expected behavior**
The material shell app launcher shows the same apps as the stock gnome app launcher.

**Screenshots**
Searching for "epip" in both app launchers.
![Material shell app launcher](https://user-images.githubusercontent.com/12911474/96696443-0f1ef100-138b-11eb-896e-35f67a5d2597.png)
![Stock gnome app launcher](https://user-images.githubusercontent.com/12911474/96696980-abe18e80-138b-11eb-92f7-5dd5a58e42cb.png)

**To Reproduce**
- Occurs on:
  - [ ] X.Org
  - [x] Wayland
- GNOME Shell version: 3.36
- Distro: OpenSUSE Tumbleweed
- Steps to reproduce, if applicable:
1. Add a new application (e.g. by adding a valid `.desktop` file to `~/.local/share/applications`).
2. Run `update-desktop-database` or wait until gnome refreshes automatically.
3. Expect the new application to be found in the stock gnome app launcher.
4. Search for the new application in the material shell app launcher. It should not be found.

**Current commit**
Version 8 (97f792cb16d94f463be44cd2e15589270d5ee723)

**Comment by Chrysostomus** [comment] 2020-10-21 09:10
I can reproduce the issue.

**Comment by lfom** [comment] 2020-10-21 18:32
As of now, App Launcher does not listed to changes to installed apps. I think the [signal needed](https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/gnome-3-36/js/ui/appDisplay.js#L423) is:

`Shell.AppSystem.get_default().connect('installed-changed', () => {  });`

If PR #418 is merged, I think it can be implemented easily since it already has the code to destroy/rebuild App Launcher.

**Comment by maxerbox** [comment] 2020-10-25 10:53
PR #418 is merged

**Closed** 2020-10-28 08:50 UTC
Labels: bug, reproductible
