### ISSUE TITLE
Dock moving to any screen side

### ISSUE THREAD

**Issue by GoshaEgorian** [material-shell/material-shell#331] opened 2020-09-24 11:02 UTC
It would be great to have settings option to move dock to any screen side (not only left but bottom, top and right as well).
Alternative, it can be implemented by drag-drop action on dock and lock option by right mouse button (window's like style).

**Comment by sebastian-xyz** [comment] 2020-09-24 15:52
Possibly a duplicate of #277

**Comment by maxerbox** [comment] 2020-09-24 17:40
Allowing the toppanel to be put on left or right would break the workflow of material shell.
#227 is for allowing it to be at the bottom.

**Closed by maxerbox** 2020-09-24 17:40 UTC
