### ISSUE TITLE
Material Shell broken after update

### ISSUE THREAD

**Issue by r0ckarong** [material-shell/material-shell#926] opened 2022-12-18 19:35 UTC
**Describe the bug**
Shell used to work. Restarted computer, was prompted for update to Version 28. Did that. Now Extension won't load with error: 
"Could not find definition of virtual function handle_event".

Tried downgrading manually to 27 but this won't work either.

**Expected behavior**
Extension just starts up as expected and works.

**Screenshots**
![Screenshot from 2022-12-18 20-27-31](https://user-images.githubusercontent.com/4920542/208315578-86a63223-3533-4f78-a168-3ae17d01ef40.png)

**To Reproduce**
- Occurs on:
  - [X] Wayland
- GNOME Shell version: 41.4
- GNOME: 41.2
- Distro: openSUSE Leap 15.4
- Steps to reproduce, if applicable:
1. Have Extension installed
2. Try to update Extension through Extensions tool or Gnome Extensions website
3. Log out as prompted
4. Log back in
5. No Material Shell

**Log data**
Output from `journalctl /usr/bin/gnome-shell`:
```
Dec 18 20:21:16 asgard gnome-shell[14600]: JS ERROR: Extension material-shell@papyelgringo: Error: Could not find definition of virtual function handle_event
                                           _init/GObject.Object._classInit/<@resource:///org/gnome/gjs/modules/core/overrides/GObject.js:466:60
                                           _init/GObject.Object._classInit@resource:///org/gnome/gjs/modules/core/overrides/GObject.js:458:10
                                           registerClass@resource:///org/gnome/gjs/modules/core/overrides/GObject.js:78:22
                                           registerGObjectClass@/home/maggus/.local/share/gnome-shell/extensions/material-shell@papyelgringo/extension.js:227:26
                                           __decorate@/home/maggus/.local/share/gnome-shell/extensions/material-shell@papyelgringo/extension.js:44:95
                                           @/home/maggus/.local/share/gnome-shell/extensions/material-shell@papyelgringo/extension.js:593:24
                                           _callExtensionInit@resource:///org/gnome/shell/ui/extensionSystem.js:420:13
                                           loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:345:27
                                           _loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:594:18
                                           collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:28
                                           _loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:573:19
                                           _enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:603:18
                                           _sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:634:18
                                           init@resource:///org/gnome/shell/ui/extensionSystem.js:56:14
                                           _initializeUI@resource:///org/gnome/shell/ui/main.js:265:22
                                           start@resource:///org/gnome/shell/ui/main.js:162:5
                                           @resource:///org/gnome/shell/ui/init.js:6:17

```

**Comment by speightashley** [comment] 2022-12-18 20:36
I'm having the exact same issue. This has happened before on upgrades and I've always had to reinstall my distribution and start from scratch because I am so used to this extension. 

Tried cleaning out the shell extensions directory and reinstalling from the shell extensions site. Didn't work. Still Error.

Tried downloading and building from source.... Still fails to start.

Why don't we just make material shell its own desktop environment? It's so far from the standard Gnome desktop environment that it deserves to be its own thing!

`Dec 18 20:33:56 ashley-ThinkPad-X1-Yoga-4th gnome-shell[2501]: JS ERROR: Extension material-shell@papyelgringo: Error: Could not find definition of virtual function handle_event
                                                               _init/GObject.Object._classInit/<@resource:///org/gnome/gjs/modules/core/overrides/GObject.js:466:60
                                                               _init/GObject.Object._classInit@resource:///org/gnome/gjs/modules/core/overrides/GObject.js:458:10
                                                               registerClass@resource:///org/gnome/gjs/modules/core/overrides/GObject.js:78:22
                                                               registerGObjectClass@/home/aspeight/.local/share/gnome-shell/extensions/material-shell@papyelgringo/extension.js:227:26
                                                               __decorate@/home/aspeight/.local/share/gnome-shell/extensions/material-shell@papyelgringo/extension.js:44:95
                                                               @/home/aspeight/.local/share/gnome-shell/extensions/material-shell@papyelgringo/extension.js:593:24
                                                               _callExtensionInit@resource:///org/gnome/shell/ui/extensionSystem.js:443:13
                                                               loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:368:27
                                                               callback@resource:///org/gnome/shell/ui/extensionDownloader.js:237:39
                                                               gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:114:13
Dec 18 20:36:08 ashley-ThinkPad-X1-Yoga-4th gnome-shell[2501]: meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
`
To Reproduce

Occurs on: Wayland
GNOME Shell version: 40.10
GNOME: 40.4
Distro: CentOS Stream 9
Steps to reproduce, if applicable:
- Extension has been installed for 3 months
- Upgrade notification from gnome-shell-extensions
- Upgraded via shell extensions page
- Material Shell deactivated
- uninstalled material shell
- reintalled material shell (Error stated on the shell extensions site)
- uninstalled
- cleaned out .local/share/shell-extensions/ folder
- downloaded source code and built from source
- errors still throughout system with just standard gnome desktop working

**Comment by PapyElGringo** [comment] 2022-12-19 10:47
You can try install manually commit https://github.com/material-shell/material-shell/commit/a9daf24178b94797d05d957ab729483a7a02b866

**Comment by speightashley** [comment] 2022-12-19 12:00
Thanks for getting back but building from source doesn't work anymore for me either.

`❯ sudo make install
[sudo] password for aspeight: 
./scripts/install.py
Installing dependencies...
Compiling...
make[1]: Entering directory '/home/aspeight/Downloads/material-shell-a9daf24178b94797d05d957ab729483a7a02b866'
rm -rf dist
mkdir dist
cp -r schemas dist
glib-compile-schemas dist/schemas/
npx sass --no-source-map src/styles/dark-theme.scss dist/style-dark-theme.css
Error reading dist/style-dark-theme.css: permission denied.
make[1]: *** [Makefile:13: dist/style-dark-theme.css] Error 66
make[1]: Leaving directory '/home/aspeight/Downloads/material-shell-a9daf24178b94797d05d957ab729483a7a02b866'
Command '['make', 'compile']' returned non-zero exit status 2.
Compilation failed
make: *** [Makefile:53: install] Error 1
`

**Comment by PapyElGringo** [comment] 2022-12-19 12:04
Try not use sudo? There is permission issue

**Comment by speightashley** [comment] 2022-12-19 13:25
I've tried both sudo and non sudo. I've tried SU and install as root as
well just in case but I was still having permission issues.

This might be like going after a mosquito with a rocket launcher, but I've
just backed up over night, switched to Manjaro where material shell is part
of the furniture! :-D

That sorted it for me

I spent ages trying to get it to work again after the update on CentOS but
it just wasn't having any of it.

**Comment by speightashley** [comment] 2022-12-19 14:42
That's cool. Switching to Manjaro has sorted it right out! Can't live
without Material shell anymore! I tried a mixture of shell extensions to
try and get the same kind of setup yesterday but nothing was cutting it at
all. It's an awesome bit of software you've done. Should be the default for
a lot of distros!

**Comment by r0ckarong** [comment] 2022-12-19 15:09
What is the last version of the extension that still works with GNOME 41
then?

**Comment by PapyElGringo** [comment] 2022-12-19 17:22
Try 26

**Comment by r0ckarong** [comment] 2022-12-21 18:23
I can manually revert the extension to version 26 and it works again but the GNOME Extensions app will try to auto-update to 28. Is there some way you can fix this on the extension side that a particular release is tied to the GNOME Shell version it works on? Or at least prevent GNOME from installing a higher incompatible version? I can work around this for a bit but if I have to do this after each logout I will just stop using Material Shell again.

**Comment by PapyElGringo** [comment] 2022-12-21 22:26
@r0ckarong you can stop using gnome extension website installation and use the git project fixed to the related commit

**Comment by r0ckarong** [comment] 2022-12-22 21:34
@PapyElGringo I'm using b96ad20ddf25b84bd64bb403c672b0aad0c6db08 as a workaround for now but I don't really think it makes a lot of sense for users to test every commit between the one that works and the one that "might work next".

**Comment by PapyElGringo** [comment] 2022-12-22 21:37
@r0ckarong you are right it just that I didn't notice the breaking change while releasing. I'm don't know if I can change which version are compatible with existing releases on gnome extension website. But I'll check after holidays

**Comment by r0ckarong** [comment] 2022-12-22 21:49
From what I understand you should limit this in the `metadata.json` file. Right now it looks like you're just amending GNOME versions there. In the case of this breaking API change, the file should reflect that it will only support until `41`.

https://github.com/material-shell/material-shell/blob/main/metadata.json#L6

The current HEAD of the project still says it supports 43, 42, 41 but this isn't true. 
Unless you had given me a clue about which commit introduced the new API behavior I wouldn't be able to find this out.

Two suggestions:

- If you introduce a breaking change that will only be supported from a particular GNOME version, please add a tag for the commit right before it and clearly label it (I have no idea how the extensions.gnome.org version works but this is probably impacted)
- Consider the development to be true only to the environments that you have tested. If you changed something for some bleeding-edge GNOME 43.x distro it does not mean that most of the users who will not be riding the bleeding edge with you can use it. It's fine to do but it shouldn't be the assumption. At least that's how I see it.

**Comment by PapyElGringo** [comment] 2023-01-03 10:48
@r0ckarong Can you try https://github.com/material-shell/material-shell/tree/fix_incompatibility_click ? it's should fix the incompatibility with older version (your version)

**Comment by r0ckarong** [comment] 2023-01-03 17:30
I checked out this branch and it seems to work fine after logout.

**Comment by PapyElGringo** [comment] 2023-01-03 17:31
Did you reinstalled or at least recompiled ? And can you confirm that the ripple effect on  tabs does work?

**Comment by r0ckarong** [comment] 2023-01-03 17:41
I reinstalled from this branch. What is the ripple effect you're talking about? What should I be looking for?

**Comment by PapyElGringo** [comment] 2023-01-06 18:23
This has been fixed by https://github.com/material-shell/material-shell/pull/937

**Closed by PapyElGringo** 2023-01-06 18:23 UTC
